//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCSN
{
    using System;
    using System.Collections.Generic;
    
    public partial class uv_users
    {
        public int id { get; set; }
        public string fullName { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<int> coin { get; set; }
        public string activeToken { get; set; }
        public Nullable<int> firstLogin { get; set; }
        public Nullable<int> status { get; set; }
        public string avatar { get; set; }
        public string describes { get; set; }
        public Nullable<int> type { get; set; }
        public System.DateTime createAt { get; set; }
    }
}
